name: Weekly Digest

on:
  workflow_dispatch:
    inputs:
      reason:
        description: "Why are you sending manually?"
        required: false
        default: "manual trigger"
  schedule:
    - cron: "0 13 * * 1" # Every Monday at 13:00 UTC

concurrency:
  group: newsletter
  cancel-in-progress: false

jobs:
  send:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Send weekly digest
        env:
          API_URL: ${{ secrets.DIGEST_API_URL }}
          CRON_SECRET: ${{ secrets.DIGEST_CRON_SECRET }}
        run: |
          if [ -z "$API_URL" ] || [ -z "$CRON_SECRET" ]; then
            echo "Missing required secrets: DIGEST_API_URL and/or DIGEST_CRON_SECRET" >&2
            exit 1
          fi
          curl -fsS -X POST "$API_URL/api/digest/send" \
            -H "Authorization: Bearer $CRON_SECRET" \
            -H "Content-Type: application/json" \
            --retry 3 --retry-delay 2 --max-time 30
